import ratlamiSevImg from '../../assets/ratlami_sev.jpg';
import khattaMeethaImg from '../../assets/khatta_meetha.jpg';
import roastedCashewsImg from '../../assets/roasted_cashews.jpg';
import desiSweetsImg from '../../assets/desi_sweets.jpg';
import murukkuImg from '../../assets/murukku_crisps.jpg';
import mathriImg from '../../assets/mathri_namkeen.jpg';

export const initialOrders = [
  {
    id: 'BIN-89423',
    placedDate: 'Aug 30, 2026 • 02:45 PM',
    estimatedDelivery: 'Sep 02, 2026',
    status: 'in-transit', // 'preparing' | 'in-transit' | 'delivered' | 'cancelled'
    statusLabel: 'In Transit',
    statusStep: 2, // 0: Placed, 1: Kitchen Frying, 2: Shipped / In Transit, 3: Delivered
    courier: {
      partner: 'BlueDart Express',
      trackingNumber: 'BD-894231902IN',
      currentLocation: 'Jaipur Sorting Hub, Rajasthan',
      lastUpdate: 'Today, 08:30 AM - Departed from Origin Facility',
    },
    items: [
      {
        id: 1,
        title: 'Artisanal Ratlami Sev (Extra Clove)',
        category: 'Sev & Bhujia',
        packSize: '500g',
        quantity: 2,
        price: 240,
        image: ratlamiSevImg,
        oilType: '100% Groundnut Oil',
      },
      {
        id: 2,
        title: 'Royal Khatta Meetha Chivda Mix',
        category: 'Chivda & Mix',
        packSize: '400g',
        quantity: 1,
        price: 190,
        image: khattaMeethaImg,
        oilType: '100% Groundnut Oil',
      },
      {
        id: 3,
        title: 'Tandoori Spiced Roasted Cashews',
        category: 'Roasted Nuts',
        packSize: '250g',
        quantity: 1,
        price: 340,
        image: roastedCashewsImg,
        oilType: 'Dry Roasted',
      },
    ],
    pricing: {
      subtotal: 1010,
      deliveryFee: 0, // Free delivery
      discount: 101, // 10% Festive code
      couponCode: 'FESTIVE10',
      totalAmount: 909,
    },
    payment: {
      method: 'UPI / Google Pay',
      transactionId: 'TXN-9842109841',
      status: 'Paid Online',
    },
    shippingAddress: {
      name: 'Binayak Patel',
      phone: '+91 98765 43210',
      addressLine: 'Flat 402, Royal Residency, Sector 5',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302017',
      addressType: 'Home',
    },
    timeline: [
      {
        title: 'Order Placed & Verified',
        time: '30 Aug 2026, 02:45 PM',
        desc: 'Payment confirmed via UPI. Kitchen ticket generated.',
        done: true,
      },
      {
        title: 'Fresh Batch Fried & FreshLock Sealed',
        time: '30 Aug 2026, 05:15 PM',
        desc: 'Master halwai fried in 100% cold-pressed groundnut oil.',
        done: true,
      },
      {
        title: 'Handed to BlueDart Express',
        time: '31 Aug 2026, 08:30 AM',
        desc: 'Air Express courier dispatched from Jaipur Central Hub.',
        done: true,
      },
      {
        title: 'Out for Final Delivery',
        time: 'Expected 02 Sep 2026',
        desc: 'Delivery agent will contact you before arrival.',
        done: false,
      },
    ],
  },
  {
    id: 'BIN-88210',
    placedDate: 'Aug 31, 2026 • 09:15 AM',
    estimatedDelivery: 'Sep 03, 2026',
    status: 'preparing',
    statusLabel: 'Preparing in Kitchen',
    statusStep: 1,
    courier: {
      partner: 'Delhivery Surface',
      trackingNumber: 'DEL-88210943IN',
      currentLocation: 'Binayak Central Kitchen, Jodhpur',
      lastUpdate: 'Fresh morning batch frying in progress.',
    },
    items: [
      {
        id: 4,
        title: 'Pure Gir Cow Ghee Besan Ladoo Box',
        category: 'Desi Sweets',
        packSize: '500g (12 Pcs)',
        quantity: 2,
        price: 320,
        image: desiSweetsImg,
        oilType: 'Pure Cow Desi Ghee',
      },
      {
        id: 5,
        title: 'Crispy Butter Murukku Chakli',
        category: 'Murukku',
        packSize: '300g',
        quantity: 1,
        price: 150,
        image: murukkuImg,
        oilType: '100% Groundnut Oil',
      },
    ],
    pricing: {
      subtotal: 790,
      deliveryFee: 40,
      discount: 0,
      couponCode: null,
      totalAmount: 830,
    },
    payment: {
      method: 'Cash on Delivery (COD)',
      transactionId: 'COD-PENDING',
      status: 'Pay ₹830 on Delivery',
    },
    shippingAddress: {
      name: 'Binayak Patel',
      phone: '+91 98765 43210',
      addressLine: 'Office 12, Corporate Business Tower, C-Scheme',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302001',
      addressType: 'Work',
    },
    timeline: [
      {
        title: 'Order Received',
        time: '31 Aug 2026, 09:15 AM',
        desc: 'Order confirmed under Kitchen Batch #42.',
        done: true,
      },
      {
        title: 'Fresh Halwai Handcrafting',
        time: '31 Aug 2026, 10:30 AM',
        desc: 'Slow cooking besan ladoos in pure bilona ghee.',
        done: true,
      },
      {
        title: 'Quality Check & Packaging',
        time: 'Scheduled today by 04:00 PM',
        desc: 'Nitrogen vacuum seal pouching.',
        done: false,
      },
      {
        title: 'Courier Dispatch',
        time: 'Scheduled tomorrow morning',
        desc: 'Express dispatch with tracking link.',
        done: false,
      },
    ],
  },
  {
    id: 'BIN-87104',
    placedDate: 'Aug 24, 2026 • 01:20 PM',
    estimatedDelivery: 'Aug 27, 2026',
    status: 'delivered',
    statusLabel: 'Delivered',
    statusStep: 3,
    deliveredOn: '27 Aug 2026, 03:40 PM',
    rating: 5,
    userReview: 'The Ratlami sev had the absolute best crunch and authentic clove punch! Delivered super fresh.',
    courier: {
      partner: 'BlueDart Express',
      trackingNumber: 'BD-871048291IN',
      currentLocation: 'Delivered to Recipient',
      lastUpdate: 'Delivered & Handed to Customer on 27 Aug',
    },
    items: [
      {
        id: 1,
        title: 'Artisanal Ratlami Sev (Extra Clove)',
        category: 'Sev & Bhujia',
        packSize: '1kg Jumbo Tin',
        quantity: 1,
        price: 460,
        image: ratlamiSevImg,
        oilType: '100% Groundnut Oil',
      },
      {
        id: 6,
        title: 'Traditional Ajwain Flaky Mathri',
        category: 'Mathri & Crisps',
        packSize: '400g',
        quantity: 2,
        price: 180,
        image: mathriImg,
        oilType: '100% Groundnut Oil',
      },
    ],
    pricing: {
      subtotal: 820,
      deliveryFee: 0,
      discount: 50,
      couponCode: 'WELCOME50',
      totalAmount: 770,
    },
    payment: {
      method: 'Credit Card (Visa)',
      transactionId: 'TXN-8710492810',
      status: 'Paid Online',
    },
    shippingAddress: {
      name: 'Binayak Patel',
      phone: '+91 98765 43210',
      addressLine: 'Flat 402, Royal Residency, Sector 5',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302017',
      addressType: 'Home',
    },
    timeline: [
      {
        title: 'Order Placed',
        time: '24 Aug 2026, 01:20 PM',
        desc: 'Order confirmed successfully.',
        done: true,
      },
      {
        title: 'Fresh Batch Frying',
        time: '24 Aug 2026, 04:00 PM',
        desc: 'Fried in fresh groundnut oil.',
        done: true,
      },
      {
        title: 'Courier Dispatched',
        time: '25 Aug 2026, 09:00 AM',
        desc: 'In transit via BlueDart.',
        done: true,
      },
      {
        title: 'Package Delivered',
        time: '27 Aug 2026, 03:40 PM',
        desc: 'Successfully received by customer.',
        done: true,
      },
    ],
  },
  {
    id: 'BIN-85912',
    placedDate: 'Aug 15, 2026 • 11:10 AM',
    estimatedDelivery: 'Aug 18, 2026',
    status: 'delivered',
    statusLabel: 'Delivered',
    statusStep: 3,
    deliveredOn: '18 Aug 2026, 12:15 PM',
    rating: null, // Not yet rated
    userReview: null,
    courier: {
      partner: 'Delhivery Express',
      trackingNumber: 'DEL-85912830IN',
      currentLocation: 'Delivered to Recipient',
      lastUpdate: 'Package delivered on 18 Aug',
    },
    items: [
      {
        id: 2,
        title: 'Royal Khatta Meetha Chivda Mix',
        category: 'Chivda & Mix',
        packSize: '500g',
        quantity: 2,
        price: 200,
        image: khattaMeethaImg,
        oilType: '100% Groundnut Oil',
      },
    ],
    pricing: {
      subtotal: 400,
      deliveryFee: 40,
      discount: 0,
      couponCode: null,
      totalAmount: 440,
    },
    payment: {
      method: 'UPI / PhonePe',
      transactionId: 'TXN-8591273918',
      status: 'Paid Online',
    },
    shippingAddress: {
      name: 'Binayak Patel',
      phone: '+91 98765 43210',
      addressLine: 'Flat 402, Royal Residency, Sector 5',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302017',
      addressType: 'Home',
    },
    timeline: [
      {
        title: 'Order Placed',
        time: '15 Aug 2026, 11:10 AM',
        desc: 'Order confirmed.',
        done: true,
      },
      {
        title: 'Fresh Batch Frying',
        time: '15 Aug 2026, 02:00 PM',
        desc: 'Prepared and packed.',
        done: true,
      },
      {
        title: 'Shipped',
        time: '16 Aug 2026, 09:30 AM',
        desc: 'Delhivery Express pickup.',
        done: true,
      },
      {
        title: 'Delivered',
        time: '18 Aug 2026, 12:15 PM',
        desc: 'Delivered to doorstep.',
        done: true,
      },
    ],
  },
  {
    id: 'BIN-84201',
    placedDate: 'Aug 02, 2026 • 06:20 PM',
    estimatedDelivery: 'Cancelled',
    status: 'cancelled',
    statusLabel: 'Cancelled & Refunded',
    statusStep: -1,
    cancelReason: 'Customer requested cancellation (changed delivery address)',
    refundStatus: '₹580 Refunded to Original UPI ID on 03 Aug',
    courier: null,
    items: [
      {
        id: 3,
        title: 'Tandoori Spiced Roasted Cashews',
        category: 'Roasted Nuts',
        packSize: '250g',
        quantity: 1,
        price: 340,
        image: roastedCashewsImg,
        oilType: 'Dry Roasted',
      },
      {
        id: 5,
        title: 'Crispy Butter Murukku Chakli',
        category: 'Murukku',
        packSize: '300g',
        quantity: 1,
        price: 150,
        image: murukkuImg,
        oilType: '100% Groundnut Oil',
      },
    ],
    pricing: {
      subtotal: 490,
      deliveryFee: 90,
      discount: 0,
      couponCode: null,
      totalAmount: 580,
    },
    payment: {
      method: 'UPI / Google Pay',
      transactionId: 'TXN-8420194821',
      status: 'Refunded (100%)',
    },
    shippingAddress: {
      name: 'Binayak Patel',
      phone: '+91 98765 43210',
      addressLine: 'Flat 402, Royal Residency, Sector 5',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302017',
      addressType: 'Home',
    },
    timeline: [
      {
        title: 'Order Placed',
        time: '02 Aug 2026, 06:20 PM',
        desc: 'Order received.',
        done: true,
      },
      {
        title: 'Cancelled by Customer',
        time: '02 Aug 2026, 07:10 PM',
        desc: 'Cancellation processed before dispatch.',
        done: true,
      },
      {
        title: 'Refund Credited',
        time: '03 Aug 2026, 11:30 AM',
        desc: 'Full refund of ₹580 credited to UPI.',
        done: true,
      },
    ],
  },
];
