import { 
  UtensilsCrossed, 
  Sparkles, 
  Cookie, 
  Nut, 
  Feather, 
  Gift, 
  Candy,
  Flame,
  Layers,
  Coffee,
  Heart,
  TrendingUp,
  Zap
} from 'lucide-react';

import ratlamiSevImg from '../../assets/ratlami_sev.jpg';
import khattaMeethaImg from '../../assets/khatta_meetha.jpg';
import heroBannerImg from '../../assets/hero_banner.jpg';
import murukkuImg from '../../assets/murukku_crisps.jpg';
import cashewsImg from '../../assets/roasted_cashews.jpg';
import desiSweetsImg from '../../assets/desi_sweets.jpg';
import mathriImg from '../../assets/mathri_namkeen.jpg';

export const getCategoryIconAndStyle = (nameOrSlug = '') => {
  const s = (nameOrSlug || '').toLowerCase();
  if (s.includes('all')) {
    return { icon: Layers, bg: 'bg-stone-100', border: 'border-stone-200', iconColor: 'text-stone-800', fallbackImg: ratlamiSevImg };
  }
  if (s.includes('sev') || s.includes('bhujia')) {
    return { icon: UtensilsCrossed, bg: 'bg-rose-50', border: 'border-rose-100', iconColor: 'text-[#981b2e]', fallbackImg: ratlamiSevImg };
  }
  if (s.includes('chivda') || s.includes('mix') || s.includes('poha')) {
    return { icon: Sparkles, bg: 'bg-amber-50', border: 'border-amber-100', iconColor: 'text-amber-700', fallbackImg: khattaMeethaImg };
  }
  if (s.includes('murukku') || s.includes('chakli') || s.includes('crisp')) {
    return { icon: Cookie, bg: 'bg-orange-50', border: 'border-orange-100', iconColor: 'text-orange-700', fallbackImg: murukkuImg };
  }
  if (s.includes('cashew') || s.includes('nut') || s.includes('badam') || s.includes('almond') || s.includes('dry fruit') || s.includes('pista')) {
    return { icon: Nut, bg: 'bg-emerald-50', border: 'border-emerald-100', iconColor: 'text-emerald-700', fallbackImg: cashewsImg };
  }
  if (s.includes('sweet') || s.includes('mithai') || s.includes('ladoo') || s.includes('jamun') || s.includes('peda')) {
    return { icon: Candy, bg: 'bg-amber-50', border: 'border-amber-100', iconColor: 'text-amber-800', fallbackImg: desiSweetsImg };
  }
  if (s.includes('mathri') || s.includes('khasta') || s.includes('farsan') || s.includes('gathiya') || s.includes('namkeen')) {
    return { icon: Flame, bg: 'bg-red-50', border: 'border-red-100', iconColor: 'text-red-700', fallbackImg: mathriImg };
  }
  if (s.includes('bake') || s.includes('diet') || s.includes('light') || s.includes('makhana')) {
    return { icon: Feather, bg: 'bg-purple-50', border: 'border-purple-100', iconColor: 'text-purple-700', fallbackImg: khattaMeethaImg };
  }
  if (s.includes('hamper') || s.includes('gift') || s.includes('box')) {
    return { icon: Gift, bg: 'bg-rose-50', border: 'border-rose-100', iconColor: 'text-[#981b2e]', fallbackImg: heroBannerImg };
  }
  return { icon: UtensilsCrossed, bg: 'bg-rose-50', border: 'border-rose-100', iconColor: 'text-[#981b2e]', fallbackImg: ratlamiSevImg };
};

export const formatApiCategory = (cat) => {
  if (!cat) return null;
  const identifier = cat.slug || cat._id || cat.id || '';
  const style = getCategoryIconAndStyle(cat.slug || cat.name || '');
  const imageUrl = cat.image?.url || (typeof cat.image === 'string' && cat.image ? cat.image : '') || style.fallbackImg;

  return {
    id: identifier,
    _id: cat._id,
    slug: cat.slug || identifier,
    name: cat.name || 'Category',
    shortName: cat.name ? cat.name.split(' ')[0] : 'Category',
    subtitle: cat.description || 'Freshly Handcrafted Delicacies',
    description: cat.description || '',
    image: imageUrl,
    rawImage: cat.image,
    icon: style.icon,
    bg: style.bg,
    border: style.border,
    iconColor: style.iconColor,
    fallbackImg: style.fallbackImg,
    status: cat.status !== undefined ? cat.status : true,
    sortOrder: cat.sortOrder || 0,
  };
};

export const formatApiProduct = (prod) => {
  if (!prod) return null;
  const prodId = prod._id || prod.id;
  
  // Extract all images safely
  let rawImagesList = [];
  if (Array.isArray(prod.images) && prod.images.length > 0) {
    rawImagesList = prod.images.map((img) => (typeof img === 'string' ? img : img?.url)).filter(Boolean);
  } else if (prod.image) {
    rawImagesList = [prod.image];
  }

  const primaryImg = rawImagesList[0] || prod.image || ratlamiSevImg;
  const secondaryImg = rawImagesList[1] || prod.secondaryImage || prod.hoverImage || null;

  const catObj =
    typeof prod.category === 'object' && prod.category !== null
      ? prod.category
      : {};
  const catName = catObj.name || prod.categoryName || 'Snacks';
  const catSlug =
    catObj.slug ||
    (typeof prod.category === 'string' && !prod.category.match(/^[0-9a-fA-F]{24}$/)
      ? prod.category
      : catName.toLowerCase().replace(/\s+/g, '-'));
  const catId = catObj._id || prod.category || catSlug;

  return {
    id: prodId,
    _id: prodId,
    title: prod.name || prod.title || 'Artisanal Snack',
    name: prod.name || prod.title || 'Artisanal Snack',
    category: catSlug,
    categoryId: catId,
    categoryName: catName,
    categorySlug: catSlug,
    tagline: prod.shortDescription || 'Prepared in 100% cold-pressed groundnut oil',
    description: prod.description || prod.shortDescription || 'Fresh handcrafted delicacy',
    price: Number(prod.sellingPrice || prod.price) || 150,
    originalPrice: Number(prod.mrp) || Math.round((Number(prod.sellingPrice || prod.price) || 150) * 1.25),
    mrp: Number(prod.mrp) || Number(prod.sellingPrice || prod.price) || 150,
    sellingPrice: Number(prod.sellingPrice || prod.price) || 150,
    weight: prod.weight || (prod.unit ? `1 ${prod.unit}` : '500g'),
    oilType: prod.oilType || '100% Cold-Pressed Groundnut Oil',
    spiciness: prod.spiciness || 'Medium Spice',
    spiceLevel: prod.spiceLevel || 2,
    shelfLife: prod.shelfLife || '90 Days',
    rating: Number(prod.rating || prod.averageRating) || 4.8,
    reviewsCount: Number(prod.reviewsCount || prod.totalReviews) || 120,
    isBestseller: Boolean(prod.isBestSeller || prod.isBestseller),
    isSpotlight: Boolean(prod.isFeatured),
    isTrending: Boolean(prod.isTrending),
    isNew: Boolean(prod.isNewArrival),
    isAvailable: prod.isAvailable !== false,
    image: primaryImg,
    secondaryImage: secondaryImg,
    images: rawImagesList.length > 0 ? rawImagesList : [primaryImg],
    ingredients: prod.ingredients || 'Artisanal Spices, Gram Flour, Groundnut Oil',
    nutritionHighlights: prod.nutritionHighlights || ['Zero Trans Fat', 'Rich in Protein'],
  };
};

export const categoriesList = [
  {
    id: 'all',
    name: 'All Categories',
    shortName: 'All',
    tagline: 'Entire Artisanal Collection',
    icon: Layers,
    bg: 'bg-stone-100',
    activeBg: 'bg-stone-900 text-white',
    iconColor: 'text-stone-800',
    border: 'border-stone-200',
    accentColor: '#1c1917',
    badge: '22+ items',
    description: 'Explore the full spectrum of authentic, artisanal snacks freshly prepared daily.',
  },
  {
    id: 'sev-bhujia',
    name: 'Sev & Bhujia',
    shortName: 'Sev & Bhujia',
    tagline: 'Crispy Rajasthani & Malwa Sev',
    icon: UtensilsCrossed,
    bg: 'bg-rose-50',
    activeBg: 'bg-[#981b2e] text-white',
    iconColor: 'text-[#981b2e]',
    border: 'border-rose-100',
    accentColor: '#981b2e',
    badge: 'Bestseller',
    description: 'Spiced gram-flour crisps fried exclusively in 100% cold-pressed groundnut oil.',
  },
  {
    id: 'chivda-mix',
    name: 'Chivda & Mix',
    shortName: 'Chivda & Mix',
    tagline: 'Sweet, Sour & Salty Mixtures',
    icon: Sparkles,
    bg: 'bg-amber-50',
    activeBg: 'bg-amber-600 text-white',
    iconColor: 'text-amber-700',
    border: 'border-amber-100',
    accentColor: '#d97706',
    badge: 'Chai Special',
    description: 'Crunchy beaten rice, roasted nuts, raisins, and aromatic spices with sweet & tangy notes.',
  },
  {
    id: 'murukku-crisps',
    name: 'Murukku & Crisps',
    shortName: 'Murukku & Crisps',
    tagline: 'South Indian Chaklis & Spirals',
    icon: Cookie,
    bg: 'bg-orange-50',
    activeBg: 'bg-orange-600 text-white',
    iconColor: 'text-orange-700',
    border: 'border-orange-100',
    accentColor: '#ea580c',
    badge: 'Ultra Crisp',
    description: 'Handcrafted South Indian spiral chaklis & crispy bites with roasted sesame & cumin.',
  },
  {
    id: 'roasted-cashews',
    name: 'Roasted Cashews',
    shortName: 'Dry Fruits',
    tagline: 'Goan Cashews & California Almonds',
    icon: Nut,
    bg: 'bg-emerald-50',
    activeBg: 'bg-emerald-700 text-white',
    iconColor: 'text-emerald-700',
    border: 'border-emerald-100',
    accentColor: '#047857',
    badge: 'Premium',
    description: 'Slow-roasted premium W240 cashews & Californian almonds in aromatic masala rubs.',
  },
  {
    id: 'desi-sweets',
    name: 'Desi Sweets',
    shortName: 'Desi Sweets',
    tagline: 'Pure Gir Cow Ghee Delicacies',
    icon: Candy,
    bg: 'bg-amber-50',
    activeBg: 'bg-amber-700 text-white',
    iconColor: 'text-amber-800',
    border: 'border-amber-100',
    accentColor: '#b45309',
    badge: 'Pure Ghee',
    description: 'Pure desi cow ghee Motichoor Ladoos, Kaju Katli, and traditional melt-in-mouth sweets.',
  },
  {
    id: 'mathri-namkeen',
    name: 'Mathri & Farsan',
    shortName: 'Mathri & Farsan',
    tagline: 'Flaky Methi Mathri & Bhakarwadi',
    icon: Flame,
    bg: 'bg-red-50',
    activeBg: 'bg-red-700 text-white',
    iconColor: 'text-red-700',
    border: 'border-red-100',
    accentColor: '#b91c1c',
    badge: 'Traditional',
    description: 'Flaky Methi Mathri, mini Bhakarwadi rolls, and royal tea-time crunch essentials.',
  },
  {
    id: 'baked-light',
    name: 'Baked & Light',
    shortName: 'Baked & Light',
    tagline: 'Guilt-Free Air Roasted Diet Snacks',
    icon: Feather,
    bg: 'bg-purple-50',
    activeBg: 'bg-purple-700 text-white',
    iconColor: 'text-purple-700',
    border: 'border-purple-100',
    accentColor: '#7e22ce',
    badge: 'Diet Friendly',
    description: 'Zero guilt, air-baked multigrain snacks, roasted makhana & diet chivdas.',
  },
  {
    id: 'festive-hampers',
    name: 'Festive Hampers',
    shortName: 'Gift Hampers',
    tagline: 'Royal Embossed Celebration Boxes',
    icon: Gift,
    bg: 'bg-rose-50',
    activeBg: 'bg-[#981b2e] text-white',
    iconColor: 'text-[#981b2e]',
    border: 'border-rose-100',
    accentColor: '#981b2e',
    badge: 'Luxury Gift',
    description: 'Opulent gifting boxes with signature namkeens, sweets, and premium dry fruits.',
  },
];

export const initialSnacksCatalog = [
  // Sev & Bhujia
  {
    id: 1,
    title: 'Authentic Ratlami Sev',
    category: 'sev-bhujia',
    categoryName: 'Sev & Bhujia',
    packOptions: [
      { weight: '250g', price: 120, originalPrice: 150 },
      { weight: '500g', price: 230, originalPrice: 290 },
      { weight: '1kg', price: 440, originalPrice: 560 },
    ],
    weight: '250g',
    price: 120,
    originalPrice: 150,
    discount: '20% OFF',
    rating: 4.8,
    reviewsCount: 1420,
    isBestseller: true,
    isSpotlight: true,
    isNew: false,
    isSpicy: true,
    spiceLevel: 3,
    spiceText: 'Fiery & Peppery',
    oilType: '100% Cold-Pressed Groundnut Oil',
    dietary: ['Pure Veg', '0% Palm Oil', 'No Preservatives'],
    bestWith: 'Ginger Chai ☕',
    image: ratlamiSevImg,
    description: 'Signature Rajasthani Sev infused with bold cloves, black pepper, and hing. Made fresh daily in small batches.',
    ingredients: 'Gram Flour (Besan), Cold-Pressed Groundnut Oil, Clove, Black Pepper, Ajwain, Asafoetida, Rock Salt.',
    shelfLife: '4 Months',
    quantity: 0,
  },
  {
    id: 2,
    title: 'Bikaneri Bhujia Special',
    category: 'sev-bhujia',
    categoryName: 'Sev & Bhujia',
    packOptions: [
      { weight: '200g', price: 110, originalPrice: 130 },
      { weight: '400g', price: 180, originalPrice: 210 },
      { weight: '1kg', price: 420, originalPrice: 500 },
    ],
    weight: '400g',
    price: 180,
    originalPrice: 210,
    discount: '14% OFF',
    rating: 4.9,
    reviewsCount: 2100,
    isBestseller: true,
    isSpotlight: true,
    isNew: false,
    isSpicy: true,
    spiceLevel: 2,
    spiceText: 'Medium Spiced',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Moth Bean Crisps'],
    bestWith: 'Evening Chai ☕',
    image: ratlamiSevImg,
    description: 'Crispy, ultra-fine bhujia prepared from freshly milled moth dal, besan, and hand-crushed spices.',
    ingredients: 'Moth Bean Flour, Besan, Cold-Pressed Groundnut Oil, Cardamom, Red Chilli, Black Pepper, Salt.',
    shelfLife: '4 Months',
    quantity: 0,
  },
  {
    id: 3,
    title: 'Ujjaini Sev (Double Clove Spicy)',
    category: 'sev-bhujia',
    categoryName: 'Sev & Bhujia',
    packOptions: [
      { weight: '250g', price: 130, originalPrice: 155 },
      { weight: '500g', price: 245, originalPrice: 299 },
    ],
    weight: '250g',
    price: 130,
    originalPrice: 155,
    discount: '16% OFF',
    rating: 4.8,
    reviewsCount: 820,
    isBestseller: false,
    isSpotlight: false,
    isNew: true,
    isSpicy: true,
    spiceLevel: 3,
    spiceText: 'Fiery Dark Clove',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Extra Spicy'],
    bestWith: 'Poha & Jalebi 🥣',
    image: ratlamiSevImg,
    description: 'Traditional Malwa recipe prepared with coarse ground besan and extra punch of dark cloves for true spice lovers.',
    ingredients: 'Besan, Extra Laung (Clove), Peppercorn, Red Chilli, Hing, Groundnut Oil, Rock Salt.',
    shelfLife: '4 Months',
    quantity: 0,
  },
  {
    id: 4,
    title: 'Nylon Fine Sev (Zero No. Chaat Sev)',
    category: 'sev-bhujia',
    categoryName: 'Sev & Bhujia',
    packOptions: [
      { weight: '200g', price: 110, originalPrice: 130 },
      { weight: '400g', price: 195, originalPrice: 240 },
    ],
    weight: '200g',
    price: 110,
    originalPrice: 130,
    discount: '15% OFF',
    rating: 4.7,
    reviewsCount: 640,
    isBestseller: false,
    isSpotlight: false,
    isNew: false,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Mild & Delicate',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Melt-in-mouth'],
    bestWith: 'Bhel & Chaat 🥗',
    image: ratlamiSevImg,
    description: 'Ultra-thin, golden delicate sev perfect for sev puri, bhel, dahi vada, and evening chai garnishing.',
    ingredients: 'Besan, Cold-Pressed Groundnut Oil, Turmeric, Sea Salt.',
    shelfLife: '4 Months',
    quantity: 0,
  },

  // Chivda & Mix
  {
    id: 5,
    title: 'Royal Khatta Meetha Mix',
    category: 'chivda-mix',
    categoryName: 'Chivda & Mix',
    packOptions: [
      { weight: '250g', price: 115, originalPrice: 140 },
      { weight: '500g', price: 200, originalPrice: 240 },
      { weight: '1kg', price: 380, originalPrice: 460 },
    ],
    weight: '500g',
    price: 200,
    originalPrice: 240,
    discount: '17% OFF',
    rating: 4.7,
    reviewsCount: 890,
    isBestseller: true,
    isSpotlight: true,
    isNew: false,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Sweet & Tangy',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Sweet & Tangy'],
    bestWith: 'Hot Masala Chai ☕',
    image: khattaMeethaImg,
    description: 'Crispy beaten rice flakes tossed with whole roasted peanuts, cashews, dried raisins, and sweet-sour amchur blend.',
    ingredients: 'Poha (Flattened Rice), Peanuts, Cashews, Raisins, Cold-Pressed Groundnut Oil, Raw Cane Sugar, Dry Mango Powder, Turmeric, Curry Leaves.',
    shelfLife: '3 Months',
    quantity: 0,
  },
  {
    id: 6,
    title: 'Crunchy Cornflakes Mixture',
    category: 'chivda-mix',
    categoryName: 'Chivda & Mix',
    packOptions: [
      { weight: '200g', price: 99, originalPrice: 120 },
      { weight: '400g', price: 175, originalPrice: 210 },
    ],
    weight: '400g',
    price: 175,
    originalPrice: 210,
    discount: '16% OFF',
    rating: 4.8,
    reviewsCount: 710,
    isBestseller: false,
    isSpotlight: false,
    isNew: true,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Sweet Masala',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Super Crunchy'],
    bestWith: 'Evening Munch 🌅',
    image: khattaMeethaImg,
    description: 'Crisp golden cornflakes blended with fried cashews, raisins, curry leaves, and sweet masala sprinkle.',
    ingredients: 'Cornflakes, Cashews, Raisins, Peanuts, Groundnut Oil, Rock Salt, Mild Spices.',
    shelfLife: '3 Months',
    quantity: 0,
  },
  {
    id: 7,
    title: 'Nashik Poha Roasted Chivda',
    category: 'chivda-mix',
    categoryName: 'Chivda & Mix',
    packOptions: [
      { weight: '250g', price: 135, originalPrice: 160 },
      { weight: '500g', price: 250, originalPrice: 300 },
    ],
    weight: '250g',
    price: 135,
    originalPrice: 160,
    discount: '15% OFF',
    rating: 4.6,
    reviewsCount: 430,
    isBestseller: false,
    isSpotlight: false,
    isNew: false,
    isSpicy: true,
    spiceLevel: 2,
    spiceText: 'Green Chilli Spiced',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Spiced Crunch'],
    bestWith: 'Irani Chai ☕',
    image: khattaMeethaImg,
    description: 'Light roasted thin poha tossed with green chillies, fried coconut slices, roasted chana dal, and curry leaves.',
    ingredients: 'Thin Poha, Coconut slices, Roasted Dal, Peanuts, Green Chilli, Groundnut Oil, Turmeric, Mustard Seeds.',
    shelfLife: '3 Months',
    quantity: 0,
  },

  // Murukku & Crisps
  {
    id: 8,
    title: 'Butter Murukku & Chakli Spirals',
    category: 'murukku-crisps',
    categoryName: 'Murukku & Crisps',
    packOptions: [
      { weight: '200g', price: 140, originalPrice: 165 },
      { weight: '400g', price: 260, originalPrice: 310 },
      { weight: '800g', price: 490, originalPrice: 590 },
    ],
    weight: '200g',
    price: 140,
    originalPrice: 165,
    discount: '15% OFF',
    rating: 4.8,
    reviewsCount: 650,
    isBestseller: true,
    isSpotlight: false,
    isNew: false,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Buttery & Aromatic',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Gluten Free'],
    bestWith: 'Filter Coffee ☕',
    image: murukkuImg,
    description: 'Golden spiral snack crafted from roasted rice flour, white butter, and aromatic sesame seeds.',
    ingredients: 'Rice Flour, Urad Dal Flour, White Butter, White Sesame, Cumin Seeds, Cold-Pressed Groundnut Oil, Himalayan Salt.',
    shelfLife: '3 Months',
    quantity: 0,
  },
  {
    id: 9,
    title: 'South Indian Ribbon Murukku Pakoda',
    category: 'murukku-crisps',
    categoryName: 'Murukku & Crisps',
    packOptions: [
      { weight: '250g', price: 145, originalPrice: 170 },
      { weight: '500g', price: 270, originalPrice: 320 },
    ],
    weight: '250g',
    price: 145,
    originalPrice: 170,
    discount: '15% OFF',
    rating: 4.7,
    reviewsCount: 310,
    isBestseller: false,
    isSpotlight: false,
    isNew: false,
    isSpicy: true,
    spiceLevel: 2,
    spiceText: 'Cumin & Chilli',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Crispy Ribbon'],
    bestWith: 'Madras Filter Coffee ☕',
    image: murukkuImg,
    description: 'Delicate, melt-in-mouth ribbon style fried crisps enriched with cumin and fresh roasted curry leaf aroma.',
    ingredients: 'Rice Flour, Besan, Butter, Asafoetida, Red Chilli Flakes, Groundnut Oil, Salt.',
    shelfLife: '3 Months',
    quantity: 0,
  },
  {
    id: 10,
    title: 'Crispy Pepper Thattai Coins',
    category: 'murukku-crisps',
    categoryName: 'Murukku & Crisps',
    packOptions: [
      { weight: '200g', price: 130, originalPrice: 150 },
      { weight: '400g', price: 245, originalPrice: 290 },
    ],
    weight: '200g',
    price: 130,
    originalPrice: 150,
    discount: '13% OFF',
    rating: 4.6,
    reviewsCount: 280,
    isBestseller: false,
    isSpotlight: false,
    isNew: true,
    isSpicy: true,
    spiceLevel: 2,
    spiceText: 'Black Pepper Punch',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Cracked Pepper'],
    bestWith: 'Green Tea 🍵',
    image: murukkuImg,
    description: 'Hand-pressed flat crispy discs with chana dal crunch and cracked black pepper punch.',
    ingredients: 'Rice Flour, Chana Dal, Black Pepper, Curry Leaves, Butter, Groundnut Oil, Salt.',
    shelfLife: '3 Months',
    quantity: 0,
  },

  // Roasted Cashews & Nuts
  {
    id: 11,
    title: 'Tandoori Masala Roasted Cashews',
    category: 'roasted-cashews',
    categoryName: 'Roasted Cashews',
    packOptions: [
      { weight: '150g', price: 290, originalPrice: 350 },
      { weight: '300g', price: 550, originalPrice: 680 },
      { weight: '500g', price: 890, originalPrice: 1100 },
    ],
    weight: '150g',
    price: 290,
    originalPrice: 350,
    discount: '17% OFF',
    rating: 4.9,
    reviewsCount: 780,
    isBestseller: true,
    isSpotlight: true,
    isNew: false,
    isSpicy: true,
    spiceLevel: 2,
    spiceText: 'Smoky Charcoal Tandoori',
    oilType: 'Slow Dry-Roasted (Zero Oil)',
    dietary: ['Pure Veg', 'High Protein', 'Keto Friendly'],
    bestWith: 'Party Platter 🍷',
    image: cashewsImg,
    description: 'Jumbo W240 Goa cashews dry-roasted without excess oil and coated in smoky charcoal tandoori spice rub.',
    ingredients: 'Jumbo Cashew Nuts, Himalayan Pink Salt, Kashmiri Chilli, Chaat Masala, Roasted Cumin, Olive Mist.',
    shelfLife: '6 Months',
    quantity: 0,
  },
  {
    id: 12,
    title: 'Slow-Roasted Pepper & Herb Almonds',
    category: 'roasted-cashews',
    categoryName: 'Roasted Cashews',
    packOptions: [
      { weight: '150g', price: 275, originalPrice: 320 },
      { weight: '300g', price: 520, originalPrice: 620 },
    ],
    weight: '150g',
    price: 275,
    originalPrice: 320,
    discount: '14% OFF',
    rating: 4.8,
    reviewsCount: 440,
    isBestseller: false,
    isSpotlight: false,
    isNew: true,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Herb & Pepper',
    oilType: 'Dry Roasted',
    dietary: ['Pure Veg', 'Keto Friendly'],
    bestWith: 'Morning Boost ☀️',
    image: cashewsImg,
    description: 'Crunchy California almonds roasted to perfection with tellicherry cracked black pepper and oregano herbs.',
    ingredients: 'Premium Almonds, Black Pepper, Himalayan Salt, Rosemary Herb, Olive Mist.',
    shelfLife: '6 Months',
    quantity: 0,
  },
  {
    id: 13,
    title: 'Himalayan Salted Roasted Pistachios',
    category: 'roasted-cashews',
    categoryName: 'Roasted Cashews',
    packOptions: [
      { weight: '150g', price: 310, originalPrice: 360 },
      { weight: '300g', price: 590, originalPrice: 700 },
    ],
    weight: '150g',
    price: 310,
    originalPrice: 360,
    discount: '14% OFF',
    rating: 4.9,
    reviewsCount: 520,
    isBestseller: false,
    isSpotlight: false,
    isNew: false,
    isSpicy: false,
    spiceLevel: 0,
    spiceText: 'Mineral Salted',
    oilType: 'In-Shell Dry Roasted',
    dietary: ['Pure Veg', 'Heart Healthy'],
    bestWith: 'Evening Snacks 🌟',
    image: cashewsImg,
    description: 'Naturally opened large pistachios roasted with Himalayan mineral pink salt for wholesome snacking.',
    ingredients: 'Whole Pistachios in Shell, Himalayan Pink Salt.',
    shelfLife: '6 Months',
    quantity: 0,
  },

  // Desi Sweets
  {
    id: 16,
    title: 'Golden Motichoor & Kaju Katli Assortment',
    category: 'desi-sweets',
    categoryName: 'Desi Sweets',
    packOptions: [
      { weight: '400g', price: 349, originalPrice: 420 },
      { weight: '800g', price: 650, originalPrice: 800 },
    ],
    weight: '400g',
    price: 349,
    originalPrice: 420,
    discount: '16% OFF',
    rating: 4.9,
    reviewsCount: 1540,
    isBestseller: true,
    isSpotlight: true,
    isNew: false,
    isSpicy: false,
    spiceLevel: 0,
    spiceText: 'Sweet Saffron & Mawa',
    oilType: 'Pure Desi Gir Cow Ghee',
    dietary: ['Pure Veg', 'Silver Leaf Decorated'],
    bestWith: 'Celebration Moments 🪔',
    image: desiSweetsImg,
    description: 'Melt-in-the-mouth Motichoor Ladoos fried in pure A2 Gir cow ghee paired with thin almond & cashew katlis.',
    ingredients: 'Besan Pearls, Desi Cow Ghee, Saffron (Kesar), Cardamom, Sugar, Goan Cashews, Silver Vark.',
    shelfLife: '15 Days (Freshly Packed)',
    quantity: 0,
  },
  {
    id: 17,
    title: 'Kesar Royal Peda Box',
    category: 'desi-sweets',
    categoryName: 'Desi Sweets',
    packOptions: [
      { weight: '300g', price: 260, originalPrice: 300 },
      { weight: '600g', price: 490, originalPrice: 580 },
    ],
    weight: '300g',
    price: 260,
    originalPrice: 300,
    discount: '13% OFF',
    rating: 4.8,
    reviewsCount: 470,
    isBestseller: false,
    isSpotlight: false,
    isNew: true,
    isSpicy: false,
    spiceLevel: 0,
    spiceText: 'Kashmiri Saffron Fudge',
    oilType: 'Pure Milk Mawa & Ghee',
    dietary: ['Pure Veg', 'Kashmiri Saffron'],
    bestWith: 'Puja & Offerings 🙏',
    image: desiSweetsImg,
    description: 'Slow-cooked condensed milk fudge infused with Kashmiri saffron strands and green cardamom essence.',
    ingredients: 'Pure Milk Khoya, Raw Cane Sugar, Saffron Threads, Green Cardamom, Pistachio Garnish.',
    shelfLife: '12 Days',
    quantity: 0,
  },
  {
    id: 18,
    title: 'Artisanal Gulab Jamun in Saffron Syrup',
    category: 'desi-sweets',
    categoryName: 'Desi Sweets',
    packOptions: [
      { weight: '500g Tin', price: 240, originalPrice: 280 },
      { weight: '1kg Tin', price: 450, originalPrice: 540 },
    ],
    weight: '500g Tin',
    price: 240,
    originalPrice: 280,
    discount: '14% OFF',
    rating: 4.9,
    reviewsCount: 890,
    isBestseller: true,
    isSpotlight: false,
    isNew: false,
    isSpicy: false,
    spiceLevel: 0,
    spiceText: 'Rose & Saffron Scented',
    oilType: 'Desi Cow Ghee Fried',
    dietary: ['Pure Veg', 'Melt-in-mouth'],
    bestWith: 'Warm Dessert 🍨',
    image: desiSweetsImg,
    description: 'Soft, spongy mawa dumplings slow fried in pure cow ghee and immersed in rose and saffron scented syrup.',
    ingredients: 'Khoya, Chenna, Desi Ghee, Sugar Syrup, Rose Water, Cardamom, Kesar.',
    shelfLife: '3 Months (Sealed Tin)',
    quantity: 0,
  },

  // Mathri & Farsan
  {
    id: 19,
    title: 'Crispy Methi Mathri & Mini Bhakarwadi',
    category: 'mathri-namkeen',
    categoryName: 'Mathri & Farsan',
    packOptions: [
      { weight: '250g', price: 135, originalPrice: 160 },
      { weight: '500g', price: 250, originalPrice: 300 },
      { weight: '1kg', price: 480, originalPrice: 580 },
    ],
    weight: '250g',
    price: 135,
    originalPrice: 160,
    discount: '15% OFF',
    rating: 4.7,
    reviewsCount: 520,
    isBestseller: true,
    isSpotlight: true,
    isNew: true,
    isSpicy: true,
    spiceLevel: 2,
    spiceText: 'Flaky Methi & Ajwain',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Tea-Time Classic'],
    bestWith: 'Adrak Masala Chai ☕',
    image: mathriImg,
    description: 'Layered flaky Rajasthani fenugreek mathris alongside sweet-spicy coconut stuffed Maharashtrian bhakarwadi rolls.',
    ingredients: 'Wheat Flour, Kasturi Methi, Ajwain, Black Pepper, Roasted Sesame, Coconut, Fennel, Cold-Pressed Groundnut Oil, Rock Salt.',
    shelfLife: '3 Months',
    quantity: 0,
  },
  {
    id: 20,
    title: 'Spicy Bhavnagri Gathiya Farsan',
    category: 'mathri-namkeen',
    categoryName: 'Mathri & Farsan',
    packOptions: [
      { weight: '250g', price: 125, originalPrice: 150 },
      { weight: '500g', price: 235, originalPrice: 285 },
    ],
    weight: '250g',
    price: 125,
    originalPrice: 150,
    discount: '16% OFF',
    rating: 4.8,
    reviewsCount: 680,
    isBestseller: false,
    isSpotlight: false,
    isNew: false,
    isSpicy: true,
    spiceLevel: 2,
    spiceText: 'Soft & Peppery',
    oilType: '100% Groundnut Oil',
    dietary: ['Pure Veg', 'Soft & Crunchy'],
    bestWith: 'Fried Green Chillies 🌶️',
    image: mathriImg,
    description: 'Authentic Gujarati tea-time gathiya prepared with ajwain, black pepper, and hing.',
    ingredients: 'Besan, Groundnut Oil, Ajwain, Black Pepper, Papad Khar, Rock Salt.',
    shelfLife: '3 Months',
    quantity: 0,
  },

  // Baked & Light
  {
    id: 14,
    title: 'Air-Baked Multigrain Diet Chivda',
    category: 'baked-light',
    categoryName: 'Baked & Light',
    packOptions: [
      { weight: '200g', price: 155, originalPrice: 180 },
      { weight: '400g', price: 290, originalPrice: 340 },
    ],
    weight: '200g',
    price: 155,
    originalPrice: 180,
    discount: '14% OFF',
    rating: 4.6,
    reviewsCount: 390,
    isBestseller: false,
    isSpotlight: false,
    isNew: false,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Mild Pink Salt',
    oilType: '95% Less Oil (Air Roasted)',
    dietary: ['Pure Veg', 'Diet Friendly', 'High Fiber'],
    bestWith: 'Morning Green Tea 🍵',
    image: khattaMeethaImg,
    description: 'Crunchy blend of air-roasted rolled oats, red rice flakes, jowar puffs, and flaxseeds with mild pink salt.',
    ingredients: 'Jowar Puffs, Rolled Oats, Red Rice Poha, Flax Seeds, Curry Leaves, Cold-Pressed Groundnut Mist, Rock Salt.',
    shelfLife: '3 Months',
    quantity: 0,
  },
  {
    id: 15,
    title: 'Crispy Roasted Pudina Makhana',
    category: 'baked-light',
    categoryName: 'Baked & Light',
    packOptions: [
      { weight: '100g', price: 165, originalPrice: 195 },
      { weight: '200g', price: 310, originalPrice: 370 },
    ],
    weight: '100g',
    price: 165,
    originalPrice: 195,
    discount: '15% OFF',
    rating: 4.8,
    reviewsCount: 620,
    isBestseller: true,
    isSpotlight: false,
    isNew: true,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Tangy Mint & Amchur',
    oilType: 'Zero Oil Slow Roasted',
    dietary: ['Pure Veg', 'Fox Nut Superfood'],
    bestWith: 'Work Desk Munching 💻',
    image: mathriImg,
    description: 'Jumbo lotus seeds slowly dry roasted and seasoned with tangy mint leaves, amchur, and black salt.',
    ingredients: 'Phool Makhana (Fox Nuts), Dried Mint Leaf Powder, Black Salt, Mango Powder, Cumin, Olive Mist.',
    shelfLife: '4 Months',
    quantity: 0,
  },

  // Festive Hampers
  {
    id: 21,
    title: 'Royal Celebration Grand Gift Hamper',
    category: 'festive-hampers',
    categoryName: 'Festive Hampers',
    packOptions: [
      { weight: '1.2kg Grand Box', price: 999, originalPrice: 1299 },
    ],
    weight: '1.2kg Grand Box',
    price: 999,
    originalPrice: 1299,
    discount: '23% OFF',
    rating: 5.0,
    reviewsCount: 420,
    isBestseller: true,
    isSpotlight: true,
    isNew: true,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Royal Assorted Treats',
    oilType: 'Artisanal Assortment',
    dietary: ['Pure Veg', 'Luxury Gift Box'],
    bestWith: 'Diwali & Wedding Gifting 🎁',
    image: heroBannerImg,
    description: 'Opulent gold-embossed gift box featuring Ratlami Sev, Masala Cashews, Khatta Meetha Mix, and Motichoor Ladoos.',
    ingredients: 'Curated assortment of 4 signature Binayak snacks in vacuum-sealed airtight gold canisters.',
    shelfLife: '3 Months',
    quantity: 0,
  },
  {
    id: 22,
    title: 'Heritage Sweets & Savouries Gift Box',
    category: 'festive-hampers',
    categoryName: 'Festive Hampers',
    packOptions: [
      { weight: '800g Box', price: 699, originalPrice: 850 },
    ],
    weight: '800g Box',
    price: 699,
    originalPrice: 850,
    discount: '18% OFF',
    rating: 4.9,
    reviewsCount: 290,
    isBestseller: false,
    isSpotlight: false,
    isNew: true,
    isSpicy: false,
    spiceLevel: 1,
    spiceText: 'Sweet & Salty Pairings',
    oilType: 'Artisanal Assortment',
    dietary: ['Pure Veg', 'Festive Edition'],
    bestWith: 'Housewarming Gifts 🏡',
    image: heroBannerImg,
    description: 'Artisanal festive box pairing spicy Bikaneri Bhujia with pure ghee Kaju Katli and Roasted Cashews.',
    ingredients: 'Bikaneri Bhujia (300g), Kaju Katli (250g), Tandoori Cashews (250g).',
    shelfLife: '2 Months',
    quantity: 0,
  }
];

export const dietaryFilterTags = [
  { id: 'all', label: 'All Snacks' },
  { id: 'bestsellers', label: '🔥 Bestsellers' },
  { id: 'spicy', label: '🌶️ Hot & Spicy' },
  { id: 'groundnut', label: '🥜 100% Groundnut Oil' },
  { id: 'sweet', label: '🍯 Desi Sweets' },
  { id: 'baked', label: '🍃 Roasted & Baked' },
  { id: 'gift', label: '🎁 Gift Hampers' },
];

export const tasteMoodCategories = [
  { id: 'all', label: 'All Moods', emoji: '✨', count: 22 },
  { id: 'chai-time', label: 'Chai-Time Crunch', emoji: '☕', filterFn: (s) => s.bestWith?.toLowerCase().includes('chai') || s.category === 'mathri-namkeen' || s.category === 'chivda-mix' },
  { id: 'spicy-fiery', label: 'Fiery & Spicy', emoji: '🌶️', filterFn: (s) => s.isSpicy || s.spiceLevel >= 2 },
  { id: 'pure-ghee', label: 'Pure Ghee Sweets', emoji: '🍯', filterFn: (s) => s.category === 'desi-sweets' },
  { id: 'high-protein', label: 'Roasted & Protein', emoji: '🥜', filterFn: (s) => s.category === 'roasted-cashews' || s.dietary.some(d => d.includes('Protein')) },
  { id: 'guilt-free', label: 'Zero Oil / Baked', emoji: '🍃', filterFn: (s) => s.category === 'baked-light' || s.oilType.toLowerCase().includes('roasted') },
];
